import { Project } from './project.model';

export function createDefaultProject(): Project {
  return {
    version: 1,
    canvas: {
      width: 210,
      height: 148,
      unit: 'mm',
      backgroundColor: '#f4f4f1',
    },
    pageSetup: {
      paperSize: 'A5',
      orientation: 'landscape',
      marginTop: 0,
      marginBottom: 0,
      marginLeft: 0,
      marginRight: 0,
      showPageBorder: true,
    },
    layers: [
      {
        id: 'layer-bottom-disc',
        name: 'Bottom disc layer',
        visible: true,
        locked: false,
        opacity: 1,
        elements: [
          {
            id: 'gear-main',
            layerId: 'layer-bottom-disc',
            type: 'gear',
            name: 'Rotating disc',
            mode: 'additive',
            x: 135,
            y: 56,
            rotation: 0,
            visible: true,
            locked: false,
            discRadius: 24,
            toothHeight: 8,
            teeth: 16,
            toothWidth: 55,
            toothShape: 60,
            centerDotRadius: 1.8,
            centerDotFill: '#392710',
            centerDotStroke: '#f6d48b',
            centerDotStrokeWidth: 0.4,
            currentRotation: 0,
            currentSlide: 0,
            fill: '#f2c469',
            stroke: '#6e4d19',
            strokeWidth: 1.2,
            interactive: true,
            rotationPoint: { x: 0, y: 0 },
            slideAxis: { x: 1, y: 0 },
            labels: [
              {
                id: 'gear-label-1',
                text: 'STR',
                angle: 0,
                offsetFromEdge: 10,
                rotation: 0,
                fontSize: 4,
                fontFamily: 'Arial, sans-serif',
                fontWeight: '400',
                fill: '#392710',
                align: 'middle',
              },
              {
                id: 'gear-label-2',
                text: 'DEX',
                angle: 90,
                offsetFromEdge: 10,
                rotation: 0,
                fontSize: 4,
                fontFamily: 'Arial, sans-serif',
                fontWeight: '400',
                fill: '#392710',
                align: 'middle',
              },
              {
                id: 'gear-label-3',
                text: 'INT',
                angle: 180,
                offsetFromEdge: 10,
                rotation: 0,
                fontSize: 4,
                fontFamily: 'Arial, sans-serif',
                fontWeight: '400',
                fill: '#392710',
                align: 'middle',
              },
              {
                id: 'gear-label-4',
                text: 'CHA',
                angle: 270,
                offsetFromEdge: 10,
                rotation: 0,
                fontSize: 4,
                fontFamily: 'Arial, sans-serif',
                fontWeight: '400',
                fill: '#392710',
                align: 'middle',
              },
            ],
          },
        ],
      },
      {
        id: 'layer-top-card',
        name: 'Top card layer',
        visible: true,
        locked: false,
        opacity: 1,
        elements: [
          {
            id: 'card-body',
            layerId: 'layer-top-card',
            type: 'rectangle',
            name: 'Card body',
            mode: 'additive',
            x: 45,
            y: 34,
            rotation: 0,
            visible: true,
            locked: false,
            width: 120,
            height: 80,
            radius: 6,
            fill: '#faf7ef',
            stroke: '#5e4b2f',
            strokeWidth: 1.2,
          },
          {
            id: 'card-window',
            layerId: 'layer-top-card',
            type: 'rectangle',
            name: 'Window',
            mode: 'subtractive',
            x: 95,
            y: 50,
            rotation: 0,
            visible: true,
            locked: false,
            width: 34,
            height: 30,
            radius: 4,
            fill: '#ffffff',
            stroke: '#5e4b2f',
            strokeWidth: 0.9,
          },
        ],
      },
    ],
  };
}
